apiVersion: v1
kind: PersistentVolume
metadata:
  name: tfx-volume
  namespace: kubeflow
  labels:
    type: local
spec:
  storageClassName: local
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt"